Update to 1.10.5
I was getting the following error:
undefined reference to `OMPI_C_MPI_NULL_COPY_FN' 
They suggest using the latest version (https://github.com/open-mpi/ompi/issues/6116)